


export const CHANGE_TASK_LIST_DATA = "CHANGE_TASK_LIST_DATA";
export const CHANGE_USER_LIST_DATA = "CHANGE_USER_LIST_DATA";
export const GET_DEPARTMENT_LIST_DATA = "GET_DEPARTMENT_LIST_DATA";
export const GET_PROJECT_LIST_DATA = "GET_PROJECT_LIST_DATA";