


export const CHANGE_TASK_LIST_DATA = "home/CHANGE_TASK_LIST_DATA";
export const CHANGE_USER_LIST_DATA = "home/CHANGE_USER_LIST_DATA";
export const GET_DEPARTMENT_LIST_DATA = "home/GET_DEPARTMENT_LIST_DATA";
export const GET_PROJECT_LIST_DATA = "home/GET_PROJECT_LIST_DATA";